

class UIAssets:
 
  def SpinnerSVG():
   return """
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid" width="200" height="200" style="shape-rendering: auto; display: block; background: transparent;" xmlns:xlink="http://www.w3.org/1999/xlink"><g><g transform="translate(78,50)">
<g transform="rotate(0)">
<circle fill-opacity="1" fill="#55aaff" r="9" cy="0" cx="0">
  <animateTransform repeatCount="indefinite" dur="0.9090909090909091s" keyTimes="0;1" values="1.3800000000000001 1.3800000000000001;1 1" begin="-0.7954545454545454s" type="scale" attributeName="transform"></animateTransform>
  <animate begin="-0.7954545454545454s" values="1;0" repeatCount="indefinite" dur="0.9090909090909091s" keyTimes="0;1" attributeName="fill-opacity"></animate>
</circle>
</g>
</g><g transform="translate(69.79898987322333,69.79898987322332)">
<g transform="rotate(45)">
<circle fill-opacity="0.875" fill="#55aaff" r="9" cy="0" cx="0">
  <animateTransform repeatCount="indefinite" dur="0.9090909090909091s" keyTimes="0;1" values="1.3800000000000001 1.3800000000000001;1 1" begin="-0.6818181818181818s" type="scale" attributeName="transform"></animateTransform>
  <animate begin="-0.6818181818181818s" values="1;0" repeatCount="indefinite" dur="0.9090909090909091s" keyTimes="0;1" attributeName="fill-opacity"></animate>
</circle>
</g>
</g><g transform="translate(50,78)">
<g transform="rotate(90)">
<circle fill-opacity="0.75" fill="#55aaff" r="9" cy="0" cx="0">
  <animateTransform repeatCount="indefinite" dur="0.9090909090909091s" keyTimes="0;1" values="1.3800000000000001 1.3800000000000001;1 1" begin="-0.5681818181818181s" type="scale" attributeName="transform"></animateTransform>
  <animate begin="-0.5681818181818181s" values="1;0" repeatCount="indefinite" dur="0.9090909090909091s" keyTimes="0;1" attributeName="fill-opacity"></animate>
</circle>
</g>
</g><g transform="translate(30.201010126776673,69.79898987322333)">
<g transform="rotate(135)">
<circle fill-opacity="0.625" fill="#55aaff" r="9" cy="0" cx="0">
  <animateTransform repeatCount="indefinite" dur="0.9090909090909091s" keyTimes="0;1" values="1.3800000000000001 1.3800000000000001;1 1" begin="-0.45454545454545453s" type="scale" attributeName="transform"></animateTransform>
  <animate begin="-0.45454545454545453s" values="1;0" repeatCount="indefinite" dur="0.9090909090909091s" keyTimes="0;1" attributeName="fill-opacity"></animate>
</circle>
</g>
</g><g transform="translate(22,50)">
<g transform="rotate(180)">
<circle fill-opacity="0.5" fill="#55aaff" r="9" cy="0" cx="0">
  <animateTransform repeatCount="indefinite" dur="0.9090909090909091s" keyTimes="0;1" values="1.3800000000000001 1.3800000000000001;1 1" begin="-0.3409090909090909s" type="scale" attributeName="transform"></animateTransform>
  <animate begin="-0.3409090909090909s" values="1;0" repeatCount="indefinite" dur="0.9090909090909091s" keyTimes="0;1" attributeName="fill-opacity"></animate>
</circle>
</g>
</g><g transform="translate(30.201010126776666,30.201010126776673)">
<g transform="rotate(225)">
<circle fill-opacity="0.375" fill="#55aaff" r="9" cy="0" cx="0">
  <animateTransform repeatCount="indefinite" dur="0.9090909090909091s" keyTimes="0;1" values="1.3800000000000001 1.3800000000000001;1 1" begin="-0.22727272727272727s" type="scale" attributeName="transform"></animateTransform>
  <animate begin="-0.22727272727272727s" values="1;0" repeatCount="indefinite" dur="0.9090909090909091s" keyTimes="0;1" attributeName="fill-opacity"></animate>
</circle>
</g>
</g><g transform="translate(49.99999999999999,22)">
<g transform="rotate(270)">
<circle fill-opacity="0.25" fill="#55aaff" r="9" cy="0" cx="0">
  <animateTransform repeatCount="indefinite" dur="0.9090909090909091s" keyTimes="0;1" values="1.3800000000000001 1.3800000000000001;1 1" begin="-0.11363636363636363s" type="scale" attributeName="transform"></animateTransform>
  <animate begin="-0.11363636363636363s" values="1;0" repeatCount="indefinite" dur="0.9090909090909091s" keyTimes="0;1" attributeName="fill-opacity"></animate>
</circle>
</g>
</g><g transform="translate(69.79898987322332,30.201010126776666)">
<g transform="rotate(315)">
<circle fill-opacity="0.125" fill="#55aaff" r="9" cy="0" cx="0">
  <animateTransform repeatCount="indefinite" dur="0.9090909090909091s" keyTimes="0;1" values="1.3800000000000001 1.3800000000000001;1 1" begin="0s" type="scale" attributeName="transform"></animateTransform>
  <animate begin="0s" values="1;0" repeatCount="indefinite" dur="0.9090909090909091s" keyTimes="0;1" attributeName="fill-opacity"></animate>
</circle>
</g>
</g><g></g></g><!-- [ldio] generated by https://loading.io --></svg>
  """